
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
('POLICY_GOD_KING', 'SLTH_TEST_ATTACH'),
('POLICY_SURVEY', 'SLTH_TEST_ATTACH');

INSERT INTO ModifierArguments (ModifierId, Name, Type, "Value") VALUES
('SLTH_TEST_ATTACH', 'AbilityType', 'ARGTYPE_IDENTITY', 'ABILITY_SLTH'),
('SLTH_TEST', 'Amount', 'ARGTYPE_IDENTITY', '5');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_TEST_ATTACH', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY_GRANCOLOMBIA_MAYA'),
('SLTH_TEST', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH');

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ABILITY_SLTH', 'LOC_ABILITY_EJERCITO_PATRIOTA_EXTRA_MOVEMENT_NAME', 'LOC_ABILITY_EJERCITO_PATRIOTA_EXTRA_MOVEMENT_DESCRIPTION', '1', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('ABILITY_SLTH', 'EJERCITO_PATRIOTA_EXTRA_MOVEMENT');

INSERT INTO Tags(Tag, Vocabulary) VALUES ('CLASS_WARRIOR', 'ABILITY_CLASS');

INSERT INTO TypeTags(Type, Tag) VALUES
('ABILITY_SLTH', 'CLASS_WARRIOR'), ('UNIT_WARRIOR', 'CLASS_WARRIOR');

INSERT INTO Types(Type, Kind) VALUES ('ABILITY_SLTH', 'KIND_ABILITY');
