UPDATE Districts SET Cost = '40' WHERE CostProgressionModel = 'COST_PROGRESSION_NUM_UNDER_AVG_PLUS_TECH' AND Cost = '27';
UPDATE Districts SET Cost = '40' WHERE CostProgressionModel = 'COST_PROGRESSION_NUM_UNDER_AVG_PLUS_TECH' AND Cost = '30';
UPDATE Districts SET Cost = '80' WHERE CostProgressionModel = 'COST_PROGRESSION_NUM_UNDER_AVG_PLUS_TECH' AND Cost = '54';
UPDATE Districts SET CostProgressionModel = 'NO_COST_PROGRESSION' WHERE CostProgressionModel = 'COST_PROGRESSION_NUM_UNDER_AVG_PLUS_TECH';

INSERT INTO Buildings(BuildingType, Name, PrereqCivic, Cost, PrereqDistrict, Description, PurchaseYield, MaxPlayerInstances) VALUES
('SLTH_BUILDING_COURTHOUSE', 'LOC_SLTH_BUILDING_COURTHOUSE_NAME', 'CIVIC_CIVIL_SERVICE', 240, 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_COURTHOUSE_DESCRIPTION', 'YIELD_GOLD', -1),
('SLTH_BUILDING_SUMMER_PALACE', 'LOC_SLTH_BUILDING_SUMMER_PALACE_NAME', 'CIVIC_CIVIL_SERVICE', 300, 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SUMMER_PALACE_DESCRIPTION', 'YIELD_GOLD', 1),
('SLTH_BUILDING_WINTER_PALACE', 'LOC_SLTH_BUILDING_WINTER_PALACE_NAME', 'CIVIC_COLONIALISM', 300, 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_WINTER_PALACE_DESCRIPTION', 'YIELD_GOLD', 1);

INSERT INTO Types(Type,	Kind) VALUES
('SLTH_BUILDING_COURTHOUSE', 'KIND_BUILDING'),
('SLTH_BUILDING_SUMMER_PALACE', 'KIND_BUILDING'),
('SLTH_BUILDING_WINTER_PALACE', 'KIND_BUILDING');

--CIVIC_CIVIL_SERVICE
--CIVIC_COLONIALISM